<?php

/*
 * Implements hook_menu();
 * */

function my_database_menu() {
    $items = array();

    $items['add'] = array(
        'title'             =>  'Add data',
        'page callback'     =>  'drupal_get_form',
        'page arguments'    =>  array('add_form'),
        'access callback'   =>  TRUE
    );

    return $items;
}

/*
 * Implements add_form();
 * */

function add_form($form, $form_state) {
    $form = array();

    $form['number'] = array(
        '#title'        =>  t('Number'),
        '#type'         =>  'textfield',
        '#maxlength'    =>  10,
        '#required'     =>  TRUE
    );

    $form['teaser'] = array(
        '#title'        =>  t('Teaser'),
        '#type'         =>  'textfield',
        '#maxlength'    =>  150,
        '#required'     =>  TRUE
    );

    $form['text'] = array(
        '#title'    =>  t('Text'),
        '#type'     =>  'textarea',
        '#required' =>  TRUE
    );

    $form['submit'] = array(
        '#type'     =>  'submit',
        '#value'    =>  t('Submit')
    );

    return $form;
}

function add_form_validate($form, &$form_state) {
    if(!ctype_digit($form_state['values']['number'])) {
        form_set_error('number', t('Field must be numeric'));
    }
}

function add_form_submit($form, &$form_state) {
    $query = db_insert('custom_table')->fields(
        array(
            'number'    =>  $form_state['values']['number'],
            'teaser'    =>  $form_state['values']['teaser'],
            'text'      =>  $form_state['values']['text']
        )
    )->execute();

    if($query > 0) {
        drupal_set_message(t("Data successfully added"));
    } else {
        drupal_set_message(t("Data unfortunately not added."), 'error');
    }
}